name: 'Composite action cannot reference vars like a workflow can'
description: 'Confirming that a composite action cannot reference vars like a workflow can'

runs:
  using: composite
  steps:
    - name: Echo from vars
      shell: bash
      run: |
        echo "Foo: ${{ vars.FOO }}"
