name: branch-information

on: 
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  print_variables:
    runs-on: ubuntu-latest
    env: 
      GITHUB_REF:      ${{ github.ref }}
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_BASE_REF: ${{ github.base_ref }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_REF_TYPE: ${{ github.ref_type }}

    steps:
    - name: print github ref variables 
      run: |
        echo "GITHUB_REF:      [$GITHUB_REF]"
        echo "GITHUB_HEAD_REF: [$GITHUB_HEAD_REF]"
        echo "GITHUB_BASE_REF: [$GITHUB_BASE_REF]"
        echo "GITHUB_REF_NAME: [$GITHUB_REF_NAME]"
        echo "GITHUB_REF_TYPE: [$GITHUB_REF_TYPE]"
