name: can-checkout-refs-heads-develop-branch

on: workflow_dispatch

jobs:
  default-working-directory:
    runs-on: ubuntu-latest
    env:
        repositoryPath: ${{ github.workspace }}
    steps:
    - name: Checkout refs/heads/develop
      uses: actions/checkout@v4
      with: 
        ref: 'refs/heads/develop' 
    - name: git status
      run: git status