name: default-working-directory-is-the-root-of-the-repository-after-checkout

on: workflow_dispatch

jobs:
  default-working-directory:
    runs-on: ubuntu-latest
    env:
        repositoryPath: ${{ github.workspace }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Print information from the working directory 
      run: |
        pwd
        echo $repositoryPath
        ls -la
        cat README.md
