name: default-working-directory-is

on: workflow_dispatch

jobs:
  default-working-directory:
    runs-on: ubuntu-latest
    env:
        repositoryPath: ${{ github.workspace }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Print working directory
      run: |
        pwd
        echo $repositoryPath
        cat README.md
