name: use-matrix

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["dev", "qa", "prod"]
    name: deploy-${{ matrix.env }}
    environment: ${{ matrix.env }}
    steps:
    - name: print-env-name
      run: echo ${{ matrix.env }}