name: use-matrix

on:
  workflow_dispatch:

jobs:
  nothing:
    runs-on: ubuntu-latest
    steps:
    - name: print-text
      run: echo "Need a step that can run all the time"
  deploy:
    name: deploy-${{ matrix.env }}
    needs: ${{ matrix.needs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: "dev"
            needs: "nothing"
          - env: "qa"
            needs: "deploy-dev"
          - env: "prod"
            needs: "deploy-qa"

    environment: ${{ matrix.env }}
    steps:
    - name: print-env-name
      run: echo ${{ matrix.env }}