name: use-matrix

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy-${{ matrix.env }}
    needs: ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['dev', 'qa', 'prod']

    environment: ${{ matrix.env }}
    steps:
    - name: print-env-name
      run: echo ${{ matrix.env }}