name: use-matrix

on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['dev', 'qa', 'prod']
    steps:
    - name: print-env-name
      run: echo ${{ matrix.env }}