name: run-git-version-container

on: workflow_dispatch

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Set version to an environment variable
      run: VER=$(docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.12.0-alpine.3.14-6.0 /repo /showvariable SemVer)
    - name: Echo the version
      run: echo $VER
