name: run-git-version-with-docker

on: workflow_dispatch

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Get build version and write to $GITHUB_ENV
      run: |
        BUILD_VERSION=$(docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.12.0-alpine.3.14-6.0 /repo /showvariable SemVer)
        echo "BUILD_VERSION=$BUILD_VERSION" >> "$GITHUB_ENV"
    - name: Echo the build version from $GITHUB_ENV
      run: echo ${{ env.BUILD_VERSION }}
