name: tag-the-build

on: workflow_dispatch

permissions:
  contents: write
  
jobs:
  tag-the-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Tag the build
      run: |
        TAG=$(date +%s); echo $TAG
        git tag $TAG
        git tag
        git push origin $TAG

